
class tests.Exceptions extends system.lang.Test
{

    function throwsFunc() static
    {
        system.io.File.out.writeln("throwsFunc: About to throw!");
        throw "Ouch!";
    }

    function simpleException() static
    {
        try
        {
            throw "Eak!";
        }
        catch (e)
        {
            system.io.File.out.writeln("simplExpression: Caught exception: " + e.message);
        }
    }

    function exceptionReturn() static
    {
        try
        {
            throw "Aaargh!";
        }
        catch (e)
        {
            system.io.File.out.writeln("exceptionReturn: Caught exception: " + e.message);
            return;
        }
        system.io.File.out.writeln("exceptionReturn: This should never get called!");
    }

    function functionException(arg)
    {
        var var0 = "var0";

        try
        {
            throwsFunc();
            system.io.File.out.writeln("functionException: Should never be called!");
        }
        catch (e1)
        {
            system.io.File.out.writeln("functionException: " + arg + ": Caught exception: " + e1.message + ", var0=" + var0);
e1.printStackTrace();
        }
        system.io.File.out.writeln("functionException: Done!");
    }

    function main() static
    {
        simpleException();
        exceptionReturn();
        functionException("test");
   }
}

